/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.h2.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoetryBO implements Serializable {

    private static final long serialVersionUID = 815217658;

    private Integer   id;
    private Integer   poetId;
    private String    title;
    private String    content;
    private Timestamp createAt;

    public PoetryBO() {}

    public PoetryBO(PoetryBO value) {
        this.id = value.id;
        this.poetId = value.poetId;
        this.title = value.title;
        this.content = value.content;
        this.createAt = value.createAt;
    }

    public PoetryBO(
        Integer   id,
        Integer   poetId,
        String    title,
        String    content,
        Timestamp createAt
    ) {
        this.id = id;
        this.poetId = poetId;
        this.title = title;
        this.content = content;
        this.createAt = createAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPoetId() {
        return this.poetId;
    }

    public void setPoetId(Integer poetId) {
        this.poetId = poetId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PoetryBO (");

        sb.append(id);
        sb.append(", ").append(poetId);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
