/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.h2;


import com.git.hui.boot.jooq.h2.tables.PoetTB;
import com.git.hui.boot.jooq.h2.tables.PoetryTB;
import com.git.hui.boot.jooq.h2.tables.records.PoetPO;
import com.git.hui.boot.jooq.h2.tables.records.PoetryPO;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PoetPO> PK_T_POET = UniqueKeys0.PK_T_POET;
    public static final UniqueKey<PoetryPO> PK_T_POETRY = UniqueKeys0.PK_T_POETRY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<PoetPO> PK_T_POET = Internal.createUniqueKey(PoetTB.POET, "PK_T_POET", PoetTB.POET.ID);
        public static final UniqueKey<PoetryPO> PK_T_POETRY = Internal.createUniqueKey(PoetryTB.POETRY, "PK_T_POETRY", PoetryTB.POETRY.ID);
    }
}
