/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.dao;


import com.git.hui.boot.jooq.dao.tables.MoneyTB;
import com.git.hui.boot.jooq.dao.tables.UserTB;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MONEY_NAME = Indexes0.MONEY_NAME;
    public static final Index MONEY_PRIMARY = Indexes0.MONEY_PRIMARY;
    public static final Index USER_NAME = Indexes0.USER_NAME;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MONEY_NAME = Internal.createIndex("name", MoneyTB.MONEY, new OrderField[] { MoneyTB.MONEY.NAME }, false);
        public static Index MONEY_PRIMARY = Internal.createIndex("PRIMARY", MoneyTB.MONEY, new OrderField[] { MoneyTB.MONEY.ID }, true);
        public static Index USER_NAME = Internal.createIndex("name", UserTB.USER, new OrderField[] { UserTB.USER.NAME }, false);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", UserTB.USER, new OrderField[] { UserTB.USER.ID }, true);
    }
}
