/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.dao;


import com.git.hui.boot.jooq.dao.tables.MoneyTB;
import com.git.hui.boot.jooq.dao.tables.UserTB;
import com.git.hui.boot.jooq.dao.tables.records.MoneyPO;
import com.git.hui.boot.jooq.dao.tables.records.UserPO;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MoneyPO, UInteger> IDENTITY_MONEY = Identities0.IDENTITY_MONEY;
    public static final Identity<UserPO, UInteger> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MoneyPO> KEY_MONEY_PRIMARY = UniqueKeys0.KEY_MONEY_PRIMARY;
    public static final UniqueKey<UserPO> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MoneyPO, UInteger> IDENTITY_MONEY = Internal.createIdentity(MoneyTB.MONEY, MoneyTB.MONEY.ID);
        public static Identity<UserPO, UInteger> IDENTITY_USER = Internal.createIdentity(UserTB.USER, UserTB.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MoneyPO> KEY_MONEY_PRIMARY = Internal.createUniqueKey(MoneyTB.MONEY, "KEY_money_PRIMARY", MoneyTB.MONEY.ID);
        public static final UniqueKey<UserPO> KEY_USER_PRIMARY = Internal.createUniqueKey(UserTB.USER, "KEY_user_PRIMARY", UserTB.USER.ID);
    }
}
