/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.dao;


import com.git.hui.boot.jooq.dao.tables.MoneyTB;
import com.git.hui.boot.jooq.dao.tables.UserTB;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = -802327415;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.money</code>.
     */
    public final MoneyTB MONEY = com.git.hui.boot.jooq.dao.tables.MoneyTB.MONEY;

    /**
     * The table <code>test.user</code>.
     */
    public final UserTB USER = com.git.hui.boot.jooq.dao.tables.UserTB.USER;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MoneyTB.MONEY,
            UserTB.USER);
    }
}
