/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoneyBO implements Serializable {

    private static final long serialVersionUID = -1774511815;

    private UInteger  id;
    private String    name;
    private Integer   money;
    private Byte      isDeleted;
    private Timestamp createAt;
    private Timestamp updateAt;

    public MoneyBO() {}

    public MoneyBO(MoneyBO value) {
        this.id = value.id;
        this.name = value.name;
        this.money = value.money;
        this.isDeleted = value.isDeleted;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
    }

    public MoneyBO(
        UInteger  id,
        String    name,
        Integer   money,
        Byte      isDeleted,
        Timestamp createAt,
        Timestamp updateAt
    ) {
        this.id = id;
        this.name = name;
        this.money = money;
        this.isDeleted = isDeleted;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getMoney() {
        return this.money;
    }

    public void setMoney(Integer money) {
        this.money = money;
    }

    public Byte getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MoneyBO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(money);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
