/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBO implements Serializable {

    private static final long serialVersionUID = 631137906;

    private UInteger id;
    private String   name;
    private String   pwd;
    private Byte     isdeleted;
    private String   created;
    private String   updated;

    public UserBO() {}

    public UserBO(UserBO value) {
        this.id = value.id;
        this.name = value.name;
        this.pwd = value.pwd;
        this.isdeleted = value.isdeleted;
        this.created = value.created;
        this.updated = value.updated;
    }

    public UserBO(
        UInteger id,
        String   name,
        String   pwd,
        Byte     isdeleted,
        String   created,
        String   updated
    ) {
        this.id = id;
        this.name = name;
        this.pwd = pwd;
        this.isdeleted = isdeleted;
        this.created = created;
        this.updated = updated;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPwd() {
        return this.pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Byte getIsdeleted() {
        return this.isdeleted;
    }

    public void setIsdeleted(Byte isdeleted) {
        this.isdeleted = isdeleted;
    }

    public String getCreated() {
        return this.created;
    }

    public void setCreated(String created) {
        this.created = created;
    }

    public String getUpdated() {
        return this.updated;
    }

    public void setUpdated(String updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserBO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(pwd);
        sb.append(", ").append(isdeleted);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
