/*
 * This file is generated by jOOQ.
 */
package com.git.hui.boot.jooq.h2.tables.records;


import com.git.hui.boot.jooq.h2.tables.PoetryTB;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoetryPO extends UpdatableRecordImpl<PoetryPO> implements Record5<Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = -158751628;

    /**
     * Setter for <code>PUBLIC.POETRY.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.POETRY.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.POETRY.POET_ID</code>.
     */
    public void setPoetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.POETRY.POET_ID</code>.
     */
    public Integer getPoetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.POETRY.TITLE</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.POETRY.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.POETRY.CONTENT</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.POETRY.CONTENT</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.POETRY.CREATE_AT</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.POETRY.CREATE_AT</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PoetryTB.POETRY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PoetryTB.POETRY.POET_ID;
    }

    @Override
    public Field<String> field3() {
        return PoetryTB.POETRY.TITLE;
    }

    @Override
    public Field<String> field4() {
        return PoetryTB.POETRY.CONTENT;
    }

    @Override
    public Field<Timestamp> field5() {
        return PoetryTB.POETRY.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPoetId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public Timestamp component5() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPoetId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public Timestamp value5() {
        return getCreateAt();
    }

    @Override
    public PoetryPO value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PoetryPO value2(Integer value) {
        setPoetId(value);
        return this;
    }

    @Override
    public PoetryPO value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PoetryPO value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public PoetryPO value5(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public PoetryPO values(Integer value1, Integer value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PoetryPO
     */
    public PoetryPO() {
        super(PoetryTB.POETRY);
    }

    /**
     * Create a detached, initialised PoetryPO
     */
    public PoetryPO(Integer id, Integer poetId, String title, String content, Timestamp createAt) {
        super(PoetryTB.POETRY);

        set(0, id);
        set(1, poetId);
        set(2, title);
        set(3, content);
        set(4, createAt);
    }
}
